name: Aura
options:
  bundleIdPrefix: com.auracolorfinder
  deploymentTarget:
    iOS: 15.0
  developmentLanguage: en
  
settings:
  base:
    PRODUCT_NAME: Aura
    PRODUCT_BUNDLE_IDENTIFIER: com.auracolorfinder.app
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic
    CURRENT_PROJECT_VERSION: 1
    MARKETING_VERSION: 1.0.0
    SWIFT_VERSION: 5.0
    TARGETED_DEVICE_FAMILY: "1,2"
    SUPPORTS_MACCATALYST: false
    
targets:
  Aura:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    
    sources:
      - path: Aura
        excludes:
          - "**/.DS_Store"
    
    settings:
      base:
        INFOPLIST_FILE: Aura/Info.plist
        CODE_SIGN_ENTITLEMENTS: Aura/Aura.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AuraAccent
        ENABLE_PREVIEWS: true
        DEVELOPMENT_ASSET_PATHS: "Aura/Resources"
        
    dependencies:
      - framework: SwiftUI.framework
        embed: false
      - framework: Combine.framework
        embed: false
      - framework: Vision.framework
        embed: false
      - framework: CoreImage.framework
        embed: false
      - framework: AVFoundation.framework
        embed: false
      - framework: CoreData.framework
        embed: false
      - framework: StoreKit.framework
        embed: false
      - framework: Photos.framework
        embed: false
      - framework: UIKit.framework
        embed: false
        
    scheme:
      testTargets:
        - AuraTests
        - AuraUITests
      gatherCoverageData: true
      
  AuraTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: AuraTests
    dependencies:
      - target: Aura
        
  AuraUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: AuraUITests
    dependencies:
      - target: Aura

